# Generated by Django 4.2.6 on 2026-03-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latecomers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='latecomers',
            name='year',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='latecomers',
            name='date',
            field=models.CharField(max_length=20),
        ),
    ]
