# Generated by Django 4.2.6 on 2026-03-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latecomers', '0002_latecomers_year_alter_latecomers_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'latelimit',
            },
        ),
    ]
