# Generated by Django 4.2.6 on 2026-03-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latecomers', '0003_latelimit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LateLimit',
        ),
        migrations.RemoveField(
            model_name='latecomers',
            name='year',
        ),
        migrations.AddField(
            model_name='latecomers',
            name='semester',
            field=models.IntegerField(default=1),
        ),
    ]
