# Generated by Django 4.2.6 on 2026-03-27 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('latecomers', '0004_delete_latelimit_remove_latecomers_year_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='latecomers',
            unique_together={('roll_no', 'date')},
        ),
    ]
