# Generated by Django 4.2.6 on 2024-08-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0004_logging'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='rollno',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
