# Generated by Django 4.2.6 on 2026-03-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0005_alter_student_rollno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='rollno',
            field=models.CharField(max_length=11),
        ),
    ]
