# Generated by Django 4.2.6 on 2026-03-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0006_alter_student_rollno'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.CharField(default='1', max_length=2),
        ),
    ]
