# Generated by Django 4.2.6 on 2026-03-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0007_student_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('startDate', models.CharField(max_length=25)),
                ('lateCount', models.IntegerField()),
                ('openingTimeLunch', models.CharField(max_length=10)),
                ('closingTimeLunch', models.CharField(max_length=10)),
                ('active', models.BooleanField()),
            ],
            options={
                'db_table': 'semester',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
