# Generated by Django 4.2.6 on 2026-03-26 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0008_semester_student_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LunchTiming',
        ),
    ]
