# Generated by Django 4.2.6 on 2026-03-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0009_delete_lunchtiming'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuedpass',
            name='issues_date',
        ),
        migrations.AddField(
            model_name='issuedpass',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='issuedpass',
            name='issued_date',
            field=models.CharField(default='2026-03-26 23:31:32', max_length=25),
        ),
        migrations.AddField(
            model_name='issuedpass',
            name='semester',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='issuedpass',
            name='valid_till',
            field=models.CharField(default='2026-03-26 23:31:32', max_length=25),
        ),
        migrations.AlterField(
            model_name='logging',
            name='time',
            field=models.CharField(max_length=25),
        ),
    ]
