# Generated by Django 4.2.6 on 2026-03-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0010_remove_issuedpass_issues_date_issuedpass_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logging',
            name='semester',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='issuedpass',
            name='issued_date',
            field=models.CharField(default='2026-03-27 00:35:28', max_length=25),
        ),
        migrations.AlterField(
            model_name='issuedpass',
            name='valid_till',
            field=models.CharField(default='2026-03-27 00:35:28', max_length=25),
        ),
    ]
