# Generated by Django 4.2.6 on 2026-03-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0011_logging_semester_alter_issuedpass_issued_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='issuedpass',
            name='issued_date',
            field=models.CharField(default='2026-03-27 15:10:16', max_length=25),
        ),
        migrations.AlterField(
            model_name='issuedpass',
            name='valid_till',
            field=models.CharField(default='2026-03-27 15:10:16', max_length=25),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='kmitrollno',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
