# Generated by Django 4.2.6 on 2026-04-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0012_remove_semester_id_remove_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedpass',
            name='issued_date',
            field=models.CharField(default='2026-04-05 14:24:20', max_length=25),
        ),
        migrations.AlterField(
            model_name='issuedpass',
            name='valid_till',
            field=models.CharField(default='2026-04-05 14:24:20', max_length=25),
        ),
    ]
