# Generated by Django 4.2.6 on 2026-04-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0015_alter_issuedpass_issued_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedpass',
            name='issued_date',
            field=models.CharField(default='2026-04-05 14:25:10', max_length=25),
        ),
        migrations.AlterField(
            model_name='issuedpass',
            name='valid_till',
            field=models.CharField(default='2026-04-05 14:25:10', max_length=25),
        ),
    ]
